name: database_repository
description: Dart package which manages the authentication domain.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.2.4
  intl: ^0.19.0
  # Legacy
  # firebase_core: ^0.6.0
  # cloud_firestore: ^0.15.0
  # firebase_storage: ^6.0.0

  # Null Safety
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9
  firebase_storage: ^11.6.10