abstract class FirebaseInitializationState {}

class FirebaseInitializationStateError extends FirebaseInitializationState {}
class FirebaseInitializationStateLoading extends FirebaseInitializationState {}
class FirebaseInitializationStateConnected extends FirebaseInitializationState {}